name: json_to_arb
description: Convert modular JSON localization files into Flutter ARB files with nested folder support.
version: 0.2.0
repository: https://github.com/karamiq/json_to_arb
homepage: https://github.com/karamiq/json_to_arb
issue_tracker: https://github.com/karamiq/json_to_arb/issues
topics:
  - flutter
  - localization
  - arb
  - i18n
  - l10n

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.26.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

executables:
  json_to_arb: